spring:
  datasource:
    username: root
    password: Mumu9568
    url: jdbc:mysql://localhost:3306/mybatis?SSL=ture&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource